version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/packages/core/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/packages/react/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/packages/vue/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"